@URLSortner_HostAddress = https://localhost:8081

POST {{URLSortner_HostAddress}}/api/Create
Content-Type: application/json

{
  //CreateRequest
}

###

POST {{URLSortner_HostAddress}}/api/Resolve/p
Content-Type: application/json

{
  //Redirect_Password
}

###

@shortID=string
GET {{URLSortner_HostAddress}}/api/Resolve/{{shortID}}

###
